In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/weatherData (1).csv",header=None,
               names=["Outlook","Temperature","Humidity","Wind","Play"])
df

     Outlook Temperature Humidity   Wind Play
0      sunny         hot     high  False   no
1      sunny         hot     high   True   no
2   overcast         hot     high  False  yes
3      rainy        mild     high  False  yes
4      rainy        cool   normal  False  yes
5      rainy        cool   normal   True   no
6   overcast        cool   normal   True  yes
7      sunny        mild     high  False   no
8      sunny        cool   normal  False  yes
9      rainy        mild   normal  False  yes
10     sunny        mild   normal   True  yes
11  overcast        mild     high   True  yes
12  overcast         hot   normal  False  yes
13     rainy        mild     high   True   no

In [ ]:
# get dummies
# pandas function
df1=pd.get_dummies(df[["Outlook","Temperature","Humidity","Wind"]],
                   drop_first=True,
                   dtype=int)
df1

,Wind,Outlook_rainy,Outlook_sunny,Temperature_hot,Temperature_mild,Humidity_normal
0,False,0,1,1,0,0
1,True,0,1,1,0,0
2,False,0,0,1,0,0
3,False,1,0,0,1,0
4,False,1,0,0,0,1
5,True,1,0,0,0,1
6,True,0,0,0,0,1
7,False,0,1,0,1,0
8,False,0,1,0,0,1
9,False,1,0,0,1,1
10,True,0,1,0,1,1
11,True,0,0,0,1,0
12,False,0,0,1,0,1
13,True,1,0,0,1,0