In [26]:
import pandas as pd

In [27]:
df=pd.read_csv("/content/Real estate.csv")
df

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1
...,...,...,...,...,...,...,...,...
409,410,2013.000,13.7,4082.01500,0,24.94155,121.50381,15.4
410,411,2012.667,5.6,90.45606,9,24.97433,121.54310,50.0
411,412,2013.250,18.8,390.96960,7,24.97923,121.53986,40.6
412,413,2013.000,8.1,104.81010,5,24.96674,121.54067,52.5
413,414,2013.500,6.5,90.45606,9,24.97433,121.54310,63.9

In [28]:
df.isnull().sum()

No                                        0
X1 transaction date                       0
X2 house age                              0
X3 distance to the nearest MRT station    0
X4 number of convenience stores           0
X5 latitude                               0
X6 longitude                              0
Y house price of unit area                0
dtype: int64

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   No                                      414 non-null    int64
 1   X1 transaction date                     414 non-null    float64
 2   X2 house age                            414 non-null    float64
 3   X3 distance to the nearest MRT station  414 non-null    float64
 4   X4 number of convenience stores         414 non-null    int64
 5   X5 latitude                             414 non-null    float64
 6   X6 longitude                            414 non-null    float64
 7   Y house price of unit area              414 non-null    float64
dtypes: float64(6), int64(2)
memory usage: 26.0 KB

In [30]:
df.columns

Index(['No', 'X1 transaction date', 'X2 house age',
       'X3 distance to the nearest MRT station',
       'X4 number of convenience stores', 'X5 latitude', 'X6 longitude',
       'Y house price of unit area'],
      dtype='object')

In [31]:
x=df.iloc[:,:7]
x

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951
2,3,2013.583,13.3,561.98450,5,24.98746,121.54391
3,4,2013.500,13.3,561.98450,5,24.98746,121.54391
4,5,2012.833,5.0,390.56840,5,24.97937,121.54245
...,...,...,...,...,...,...,...
409,410,2013.000,13.7,4082.01500,0,24.94155,121.50381
410,411,2012.667,5.6,90.45606,9,24.97433,121.54310
411,412,2013.250,18.8,390.96960,7,24.97923,121.53986
412,413,2013.000,8.1,104.81010,5,24.96674,121.54067
413,414,2013.500,6.5,90.45606,9,24.97433,121.54310

In [32]:
y=df["Y house price of unit area"]
y

0      37.9
1      42.2
2      47.3
3      54.8
4      43.1
       ...
409    15.4
410    50.0
411    40.6
412    52.5
413    63.9
Name: Y house price of unit area, Length: 414, dtype: float64

In [33]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=42)

In [34]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(xtrain)
xtrain=scaler.transform(xtrain)
xtrain

array([[-1.58079708e-01,  1.12832111e-03,  2.34401494e+00, ...,
         9.68041591e-01, -1.47065968e-01,  4.55057247e-01],
       [ 2.00248043e-01,  2.96350853e-01, -8.21281376e-01, ...,
        -4.91703665e-02, -7.43116969e-01, -1.35592638e+00],
       [-1.75349136e+00, -1.77732066e+00, -9.00855865e-01, ...,
        -3.88241019e-01, -5.04054791e-01, -1.42748297e+00],
       ...,
       [ 5.07386116e-01,  5.91573384e-01, -5.73716301e-01, ...,
        -1.06638232e+00,  4.22511704e-01, -2.29077262e-01],
       [ 1.17285194e+00, -1.18687560e+00, -1.12189611e+00, ...,
         6.28970939e-01,  5.22789463e-01,  7.53989921e-01],
       [-9.25924889e-01, -2.97651108e-01, -1.43135245e+00, ...,
         6.28970939e-01, -2.90663719e-01,  4.68432311e-01]])

In [35]:
xtest=scaler.transform(xtest)
xtest

array([[ 1.25816807e+00,  1.12832111e-03, -1.43135245e+00,
        -7.12135284e-01,  6.28970939e-01, -2.90663719e-01,
         4.68432311e-01],
       [ 1.18991517e+00, -5.92873640e-01, -3.61517666e-01,
        -4.66555441e-01,  2.89900286e-01, -3.35588155e-01,
         2.33031189e-01],
       [ 1.38614227e+00, -2.97651108e-01, -1.52861016e+00,
        -6.45997083e-01, -1.06638232e+00,  4.38556146e-01,
        -2.20383470e-01],
       [ 1.60796421e+00, -8.88096171e-01, -4.05725715e-01,
        -7.31423027e-01, -1.06638232e+00,  3.51113940e-01,
        -2.70539959e-01],
       [ 1.35201582e+00, -1.77732066e+00,  2.57395022e-01,
         9.25528139e-01, -3.88241019e-01, -4.90417016e-01,
        -1.43885177e+00],
       [-1.18187328e+00,  1.48079788e+00,  1.34491303e+00,
        -5.22215128e-01,  1.30711224e+00,  5.24393908e-01,
         3.50731750e-01],
       [ 4.39133211e-01, -8.88096171e-01, -1.22794200e-01,
        -6.33407209e-01,  2.89900286e-01,  1.01856270e+00,
         6.41639386e-01],
       [-6.01723591e-01,  2.96350853e-01, -9.62693710e-02,
        -6.33407209e-01,  2.89900286e-01,  1.01856270e+00,
         6.41639386e-01],
       [-1.00270941e+00, -8.88096171e-01,  1.29186337e+00,
         7.13147482e-02, -1.40545298e+00, -1.61513236e+00,
        -2.09014666e-01],
       [-1.19893651e+00,  1.48079788e+00, -9.45063914e-01,
        -7.96938691e-01,  1.64618290e+00,  4.00851708e-01,
         6.16226765e-01],
       [-7.89419079e-01,  1.18557534e+00,  7.08317123e-01,
         4.30986790e-01, -3.88241019e-01, -2.49750393e-01,
        -1.12320027e+00],
       [-6.78508109e-01,  1.18557534e+00, -1.17494577e+00,
         8.94484344e-01, -3.88241019e-01, -5.08868123e-01,
        -1.40742037e+00],
       [ 1.07047258e+00, -1.18687560e+00, -1.07768806e+00,
         6.64120335e-01, -7.27311672e-01,  1.18221601e+00,
        -1.09711890e+00],
       [-1.32691071e+00, -1.18687560e+00,  1.27418015e+00,
         8.30762286e-02, -1.40545298e+00, -1.57662570e+00,
        -2.53821130e-01],
       [-7.21166174e-01, -2.97651108e-01,  1.88425123e+00,
        -2.09618199e-01, -4.91703665e-02,  7.25751648e-01,
         5.91553611e-02],
       [ 1.41173711e+00,  8.90352813e-01, -2.28893518e-01,
         5.40741147e-01, -7.27311672e-01, -3.90139256e-01,
        -1.16332546e+00],
       [-1.31837909e+00,  8.90352813e-01,  1.44217074e+00,
        -5.66039820e-01,  1.30711224e+00,  2.57253957e-01,
         4.48369715e-01],
       [ 6.86549992e-01, -1.18687560e+00, -1.22799543e+00,
        -8.24882227e-01,  9.68041591e-01, -9.54101374e-01,
         2.15643606e-01],
       [ 1.31788936e+00, -8.88096171e-01,  9.88337050e-04,
         9.88273578e-01, -4.91703665e-02, -6.02728106e-01,
        -1.44888307e+00],
       [-1.07949393e+00, -2.97651108e-01, -1.93527079e-01,
        -5.56146625e-01,  9.68041591e-01, -1.59099299e-01,
         7.19214755e-01],
       [-8.06482306e-01, -5.92873640e-01,  1.20344727e+00,
         4.38839727e+00, -1.06638232e+00, -2.05234339e+00,
        -3.68184996e+00],
       [-1.71936491e+00,  8.90352813e-01,  5.40379960e-02,
         5.95002827e-01, -3.88241019e-01, -1.62308187e-01,
        -1.27233223e+00],
       [ 1.39467388e+00,  2.96350853e-01, -1.05116323e+00,
        -5.50153722e-01,  2.89900286e-01,  8.05171633e-01,
         5.72757807e-01],
       [-6.27318430e-01,  1.18557534e+00, -3.26151226e-01,
        -6.08946816e-01,  6.28970939e-01, -3.51632597e-01,
         5.94157909e-01],
       [ 9.33966772e-01, -1.48209813e+00, -3.34992836e-01,
         2.58019485e+00, -1.40545298e+00, -2.44543221e+00,
        -2.00996699e+00],
       [ 1.63355905e+00, -1.18687560e+00, -4.05725715e-01,
        -7.17153176e-01, -1.06638232e+00,  3.64751715e-01,
        -2.72546219e-01],
       [ 1.74653204e-01, -1.18687560e+00, -9.62693710e-02,
         2.47936912e+00, -1.40545298e+00, -2.16465448e+00,
        -2.02735458e+00],
       [-1.02830425e+00, -1.18687560e+00, -1.52861016e+00,
        -6.45997083e-01, -1.06638232e+00,  4.38556146e-01,
        -2.20383470e-01],
       [-9.94177794e-01, -8.88096171e-01,  2.08760826e+00,
        -7.33503468e-01,  2.89900286e-01, -2.43332617e-01,
         4.26300860e-01],
       [-3.20180357e-01, -2.97651108e-01,  2.12297469e+00,
        -5.40851520e-01, -4.91703665e-02,  1.11723602e+00,
         7.16539742e-01],
       [-1.54020103e+00,  1.18557534e+00,  7.61366782e-01,
         2.84525864e+00, -1.40545298e+00, -1.69054124e+00,
        -2.54229453e+00],
       [-5.93191977e-01,  5.91573384e-01, -1.07768806e+00,
         4.11337726e-01, -3.88241019e-01,  2.24362852e-01,
        -1.17803803e+00],
       [-9.08861663e-01, -1.77732066e+00,  1.36259625e+00,
        -5.48609837e-01,  6.28970939e-01, -4.29448138e-01,
         5.76101573e-01],
       [-1.12215199e+00, -5.92873640e-01,  6.28796058e-02,
         2.92111196e-01, -1.06638232e+00, -1.40495018e+00,
         1.00209735e+00],
       [-1.51460620e+00,  2.96350853e-01, -6.97445415e-02,
        -6.05177189e-01,  6.28970939e-01,  7.28158314e-01,
         5.96832922e-01],
       [ 6.78018379e-01, -2.97651108e-01,  1.80467674e+00,
        -4.68106891e-01, -1.40545298e+00,  2.27571740e-01,
         5.51428420e-02],
       [ 6.43891926e-01, -8.88096171e-01, -1.00695518e+00,
        -7.96938691e-01,  1.64618290e+00,  4.00851708e-01,
         6.16226765e-01],
       [ 1.69328034e+00, -5.92873640e-01, -3.17309617e-01,
         2.48535471e+00, -1.40545298e+00, -2.22883225e+00,
        -2.01130450e+00],
       [ 9.78686859e-02,  1.48079788e+00,  1.17692244e+00,
        -5.16814863e-01,  1.98525355e+00,  9.54384939e-01,
         2.37043708e-01],
       [ 1.28376291e+00, -2.97651108e-01,  2.13181630e+00,
        -6.40084190e-01,  1.30711224e+00,  3.30256166e-01,
         4.71107323e-01],
       [-1.66817523e+00,  1.48079788e+00,  1.62784454e+00,
        -3.95033502e-01, -7.27311672e-01,  1.04824492e+00,
         8.22871499e-01],
       [ 8.57182254e-01,  1.12832111e-03,  3.54652730e-01,
        -4.29086290e-01, -4.91703665e-02,  3.94433932e-01,
         2.84525185e-01],
       [-1.79614943e+00, -8.88096171e-01,  1.30070498e+00,
        -8.01524904e-01,  1.98525355e+00,  1.09477380e+00,
         4.24963354e-01],
       [ 9.08371933e-01, -1.48209813e+00, -1.49319030e-01,
        -2.52314766e-01, -7.27311672e-01,  6.91256099e-01,
         4.17677783e-02],
       [ 5.24449342e-01, -1.48209813e+00, -3.79200885e-01,
        -4.66555441e-01,  2.89900286e-01, -3.35588155e-01,
         2.33031189e-01],
       [-7.38229401e-01, -8.88096171e-01, -6.53290790e-01,
        -6.41755450e-01,  9.68041591e-01,  4.77062805e-01,
         7.70708750e-01],
       [ 5.15917729e-01, -8.88096171e-01,  3.63547763e-02,
        -4.99932455e-01,  1.30711224e+00,  9.36733630e-03,
         7.36602338e-01],
       [-2.26332613e-01, -1.48209813e+00, -2.81943177e-01,
         1.27939797e+00, -1.40545298e+00, -1.15385467e+00,
         1.86278270e+00],
       [ 5.50044182e-01, -1.77732066e+00, -1.39598601e+00,
        -8.52093580e-01,  9.68041591e-01, -1.29417082e-01,
         4.77126102e-01],
       [ 1.27523130e+00, -1.77732066e+00,  1.38027947e+00,
        -7.99532121e-01,  1.98525355e+00,  1.09637825e+00,
         4.23625847e-01],
       [ 1.23463525e-01,  2.96350853e-01, -1.43135245e+00,
        -7.12135284e-01,  6.28970939e-01, -2.90663719e-01,
         4.68432311e-01],
       [ 1.23257323e+00,  2.96350853e-01, -1.19262899e+00,
        -5.55668123e-01,  2.89900286e-01,  9.23900500e-01,
         6.70395773e-01],
       [ 1.30935775e+00,  8.90352813e-01,  1.59247811e+00,
        -3.66309357e-01,  9.68041591e-01,  7.85918304e-01,
         1.85549713e-01],
       [ 5.41512569e-01,  1.12832111e-03,  9.02832539e-01,
        -5.47317661e-01,  9.68041591e-01,  2.98167283e-01,
         4.04900758e-01],
       [-3.03117131e-01, -2.97651108e-01,  1.14155600e+00,
        -4.83048321e-01, -3.88241019e-01,  5.75006607e-02,
         2.47075006e-01],
       [-1.17334167e+00,  1.12832111e-03, -3.08468007e-01,
         2.48535471e+00, -1.40545298e+00, -2.22883225e+00,
        -2.01130450e+00],
       [-1.43782168e+00,  8.90352813e-01,  1.66321098e+00,
        -4.44163648e-01,  2.89900286e-01, -5.04054791e-01,
         2.47075006e-01],
       [-3.88433262e-01, -8.88096171e-01, -3.17309617e-01,
         1.45515768e-01, -1.06638232e+00,  6.10231669e-01,
         1.33914896e+00],
       [-1.13921522e+00, -1.18687560e+00,  2.83919851e-01,
         9.25528139e-01, -3.88241019e-01, -4.90417016e-01,
        -1.43885177e+00],
       [-1.46341652e+00,  1.12832111e-03, -9.62693710e-02,
        -6.33407209e-01,  2.89900286e-01,  1.01856270e+00,
         6.41639386e-01],
       [ 1.62502744e+00, -2.97651108e-01, -8.56647816e-01,
         9.17224467e-01, -3.88241019e-01, -5.04054791e-01,
        -1.42748297e+00],
       [-1.58285910e+00, -2.97651108e-01,  1.06198152e+00,
         3.52165218e-01, -7.27311672e-01,  4.88293914e-01,
        -1.11183147e+00],
       [-4.73749394e-01,  1.12832111e-03, -3.08468007e-01,
         2.48535471e+00, -1.40545298e+00, -2.22883225e+00,
        -2.01130450e+00],
       [-2.60459065e-01, -1.77732066e+00,  8.49782880e-01,
         2.78735166e+00, -1.40545298e+00, -1.63278125e+00,
        -2.51955692e+00],
       [ 1.16432033e+00,  1.48079788e+00,  9.82994687e-03,
         4.46383422e+00, -1.06638232e+00, -9.74156926e-01,
        -4.03628915e+00],
       [ 4.73259664e-01,  2.96350853e-01,  4.51963862e-02,
         5.95002827e-01, -3.88241019e-01, -1.62308187e-01,
        -1.27233223e+00],
       [-1.60845394e+00, -8.88096171e-01, -2.28893518e-01,
         2.47132558e-01, -1.06638232e+00, -1.38730129e+00,
         9.72003459e-01],
       [-1.40369522e+00,  8.90352813e-01,  3.90019169e-01,
        -4.89801284e-01,  1.64618290e+00,  7.75562126e-02,
         7.15202236e-01],
       [-1.13068360e+00, -8.88096171e-01,  1.84888479e+00,
        -4.17047691e-01, -7.27311672e-01,  5.33218350e-01,
        -5.04494472e-03],
       [-4.99344233e-01,  5.91573384e-01, -4.67616984e-01,
         2.47132558e-01, -1.06638232e+00, -1.38730129e+00,
         9.72003459e-01],
       [-1.09655715e+00, -2.97651108e-01, -3.61517666e-01,
        -7.47206583e-01,  9.68041591e-01, -1.67121520e-01,
         5.77439080e-01],
       [-1.14774683e+00,  1.48079788e+00,  1.64552776e+00,
        -3.64450117e-01, -3.88241019e-01,  6.33496110e-01,
         2.53093785e-01],
       [-1.30984748e+00, -8.88096171e-01, -1.21915382e+00,
        -8.24882227e-01,  9.68041591e-01, -9.54101374e-01,
         2.15643606e-01],
       [-8.57671984e-01, -2.97651108e-01, -8.12439767e-01,
        -7.85135240e-01,  2.89900286e-01, -2.08034846e-01,
         4.53719740e-01],
       [-1.59139071e+00, -5.92873640e-01,  1.97266733e+00,
        -4.76039620e-01, -4.91703665e-02,  3.36673942e-01,
         3.32006661e-01],
       [-1.65111201e+00, -1.48209813e+00,  3.63547763e-02,
        -5.82813272e-01, -1.06638232e+00,  4.89898358e-01,
        -1.80258279e-01],
       [ 2.34374496e-01, -2.97651108e-01, -3.96884105e-01,
        -2.68690303e-01, -1.40545298e+00,  5.89373896e-01,
        -5.82178944e-01],
       [ 1.65915389e+00, -1.77732066e+00,  5.04960097e-01,
        -7.63603582e-01,  6.28970939e-01, -1.01908136e+00,
         2.51756278e-01],
       [-1.53166942e+00, -1.48209813e+00,  1.08850635e+00,
        -2.38634429e-01,  9.68041591e-01,  1.08113603e+00,
         1.30113913e-02],
       [ 6.18297087e-01,  8.90352813e-01,  1.43332913e+00,
         7.55756765e-01, -7.27311672e-01,  1.39640930e+00,
        -1.03291859e+00],
       [-4.56686167e-01,  2.96350853e-01, -1.05110981e-01,
        -2.00374052e-01, -4.91703665e-02,  7.64258308e-01,
         5.04615697e-02],
       [-6.42319635e-02, -1.77732066e+00, -1.49319030e-01,
        -6.33407209e-01,  2.89900286e-01,  1.01856270e+00,
         6.41639386e-01],
       [-2.15738978e-02, -1.48209813e+00, -5.11825033e-01,
         2.47132558e-01, -1.06638232e+00, -1.38730129e+00,
         9.72003459e-01]])

In [36]:
from sklearn.neighbors import KNeighborsRegressor
model=KNeighborsRegressor(n_neighbors=7)
model

KNeighborsRegressor(n_neighbors=7)

In [37]:
model.fit(xtrain,ytrain)

KNeighborsRegressor(n_neighbors=7)

In [38]:
ypred=model.predict(xtest)
ypred

array([45.21428571, 38.88571429, 52.78571429, 39.65714286, 25.4       ,
       40.58571429, 42.84285714, 50.27142857, 21.14285714, 56.77142857,
       24.18571429, 27.25714286, 26.78571429, 25.77142857, 38.82857143,
       26.77142857, 41.47142857, 43.34285714, 24.37142857, 37.7       ,
       15.65714286, 25.48571429, 48.74285714, 41.32857143, 17.92857143,
       39.65714286, 15.6       , 45.41428571, 42.94285714, 39.38571429,
       18.71428571, 25.77142857, 41.51428571, 25.05714286, 48.6       ,
       39.84285714, 50.5       , 18.14285714, 52.94285714, 42.37142857,
       42.12857143, 46.55714286, 42.07142857, 37.9       , 40.31428571,
       48.7       , 43.6       , 24.9       , 45.34285714, 41.5       ,
       47.57142857, 48.1       , 47.25714286, 40.64285714, 38.75714286,
       17.05714286, 47.07142857, 30.81428571, 24.52857143, 48.7       ,
       25.2       , 30.84285714, 16.58571429, 15.38571429, 17.51428571,
       26.92857143, 25.05714286, 47.6       , 36.62857143, 26.3       ,
       39.85714286, 39.27142857, 50.07142857, 45.44285714, 40.97142857,
       38.42857143, 51.7       , 38.17142857, 43.45714286, 36.37142857,
       46.04285714, 42.14285714, 25.07142857])

In [39]:
ytest.values

array([45.1, 42.3, 52.2, 37.3, 22.8, 36.3, 53. , 51.4, 16.1, 59. , 30.6,
       30.7, 35.6, 13.7, 62.9, 30.5, 41.9, 54.4, 29.5, 43.7, 12.2, 22.1,
       49.5, 47.4, 18.6, 28.5, 14.7, 45.4, 41. , 35.1, 22.1, 28.9, 30.5,
       26.5, 49.3, 37. , 56.3, 15.4, 48.5, 63.3, 50.5, 42.2, 37.9, 37.5,
       40.5, 57.4, 26.5, 21.8, 49.7, 47.1, 49. , 60.7, 33.1, 41. , 36.5,
       20. , 34.7, 30.6, 25.6, 46.2, 27.7, 27. , 15.6, 15.5, 11.2, 23.7,
       24.6, 42. , 29.8, 28.9, 48.1, 36.8, 53.5, 51.6, 38.8, 37.4, 40.6,
       37.2, 25. , 23.5, 35.6, 46.1, 26.2])